version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: crypto_trading
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: trading123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trader"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://trader:trading123@postgres:5432/crypto_trading
      - REDIS_URL=redis://redis:6379
      - BYBIT_API_KEY=${BYBIT_API_KEY}
      - BYBIT_API_SECRET=${BYBIT_API_SECRET}
      - BYBIT_TESTNET=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./ml_worker/saved_models:/app/ml_worker/saved_models

  ml-worker:
    build: .
    command: python ml_worker/worker.py
    environment:
      - DATABASE_URL=postgresql://trader:trading123@postgres:5432/crypto_trading
      - REDIS_URL=redis://redis:6379
      - BYBIT_API_KEY=${BYBIT_API_KEY}
      - BYBIT_API_SECRET=${BYBIT_API_SECRET}
      - BYBIT_TESTNET=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./ml_worker/saved_models:/app/ml_worker/saved_models

volumes:
  postgres_data:
  redis_data: