[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python -m backend.main"

[[services]]
name = "backend"
source = "."

[[services]]
name = "frontend"
source = "./frontend"
build.command = "npm run build"
start.command = "npm start"

[[services]]
name = "ml-worker"
source = "."
startCommand = "python ml_worker/worker.py"

[[services]]
name = "frontend"
source = "./frontend"
startCommand = "npm start"

[environments.production.variables]
BYBIT_API_KEY = "${{BYBIT_API_KEY}}"
BYBIT_API_SECRET = "${{BYBIT_API_SECRET}}"
OPENAI_API_KEY = "${{OPENAI_API_KEY}}"
DATABASE_URL = "${{DATABASE_URL}}"
REDIS_URL = "${{REDIS_URL}}"