[services.backend]
source = "backend"

[services.backend.build]  
builder = "nixpacks"

[services.backend.deploy]
startCommand = "uvicorn test_main:app --host 0.0.0.0 --port $PORT"

[services.frontend]
source = "frontend"

[services.frontend.build]  
builder = "nixpacks"

[services.frontend.deploy]
startCommand = "npm start"